apiVersion: apps/v1
kind: Deployment
metadata:
  name: lesson3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lesson3
  template:
    metadata:
      labels:
        app: lesson3
    spec:
      containers:
      - name: lesson3
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      - name: lesson3-multitool
        image: wbitt/network-multitool
        env:
          - name: HTTP_PORT
            value: "3232"
        ports:
        - containerPort: 2323
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
