apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  labels:
    app: pod-netology
spec:
  containers:
    - name: hello-world
      image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
      ports:
      - containerPort: 8080
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
