apiVersion: apps/v1
kind: Deployment
metadata:
  name: lesson4
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lesson4
  template:
    metadata:
      labels:
        app: lesson4
    spec:
      containers:
      - name: lesson4-nginx
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      - name: lesson4-multitool
        image: wbitt/network-multitool
        env:
          - name: HTTP_PORT
            value: "8080"
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
