apiVersion: v1
kind: PersistentVolume
metadata:
  name: lesson7-volume
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data