apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: lesson9 
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]