apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-nginx-app.fullname" . }}
  labels:
    app: {{ include "my-nginx-app.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: {{ include "my-nginx-app.name" . }}