# https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lesson5-ingress
  namespace: lesson5
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: "nginx"
  rules:
  - host: ingress-k8s.midnas.ru
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: lesson5-frontend
            port:
              number: 80
      - path: /api
        pathType: Exact
        backend:
          service:
            name: lesson5-backend
            port:
              number: 80