kind: Service
apiVersion: v1
metadata:
  name:  lesson4-svc
spec:
  selector:
    app:  lesson4
  type:  ClusterIP
  ports:
  - name:  lesson4-port-nginx
    port:  9001
    targetPort:  80
  - name: lesson4-port-multitool
    port: 9002
    targetPort: 8080